pipeline {
    agent any
    stages {
        stage('Preparar entorno') {
            steps {
                dir('template-main/RA5/RA5_1') {
                    sh 'python3 -m venv venv'
                    sh '. venv/bin/activate && pip install -r requirements.txt'
                }
            }
        }
        stage('Ejecutar pruebas') {
            steps {
                dir('template-main/RA5/RA5_1') {
                    sh '. venv/bin/activate && python3 -m unittest test_calculator.py'
                }
            }
        }
    }
}
